version: '3.0'

services:
  postgres:
    container_name: supply_postgres
    image: postgres:16
    restart: no
    volumes:
      - /db/pg:/var/lib/data
    ports:
      - 6969:5432
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: supply
